import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";



export const metadata: Metadata = {
  title: "Saber Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
         <header><div>Saber</div></header>
         <nav>
          <ul>
            <li><Link href="/">Home</Link></li>
            <li><Link href="/dashboard">Dashboard Home</Link></li>
          </ul>
         </nav>
        <main>{children}</main>
        <footer><div>Footer</div></footer>
      </body>
    </html>
  );
}
